application: atlantis-college
version: 1
runtime: python
api_version: 1

handlers:
- url: /(.*\.(gif|png|jpg|ico|svg|js|css))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|svg|js|css))

- url: /assets/css/images/(.*\.(gif|png|jpg|ico|svg))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|svg))

- url: /assets/fonts/(.*\.(eot|svg|ttf|woff))
  static_files: \1
  upload: (.*\.(eot|svg|ttf|woff))

- url: /robots.txt
  static_files: robots.txt
  upload: robots.txt 

- url: .*
  script: main.py
